version: "3.8"

services:
  metrics:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:80
    volumes:
      - ./:/app
    environment:
      - MONGO_METRICS_URL=${MONGO_METRICS_URL}


